// script.js — Updated with category buttons, subcategories, and animated chatbot support

document.addEventListener("DOMContentLoaded", function () { const categoryButtons = document.querySelectorAll(".category-button"); const contentContainer = document.getElementById("content-container");

categoryButtons.forEach((button) => { button.addEventListener("click", () => { const category = button.dataset.category; showSubcategories(category); }); });

function showSubcategories(category) { const subcategories = getSubcategories(category); contentContainer.innerHTML = ""; subcategories.forEach((item) => { const card = document.createElement("div"); card.className = "job-card animate-slidein"; card.innerHTML = <h3>${item.title}</h3><ul>${item.links .map((link) => <li><a href="${link.url}" target="_blank">${link.name}</a></li>)  .join("")}</ul>; contentContainer.appendChild(card); }); }

function getSubcategories(category) { switch (category) { case "gov-jobs": return [ { title: "UPSC Exams", links: [ { name: "Official UPSC Website", url: "https://upsc.gov.in" }, { name: "Previous Papers", url: "https://www.upsc.gov.in/examinations/previous-question-papers" }, { name: "Syllabus & Notifications", url: "https://www.upsc.gov.in/examinations/syllabus" } ]}, { title: "SSC Exams", links: [ { name: "SSC Official", url: "https://ssc.nic.in" }, { name: "CHSL Info", url: "https://ssc.nic.in/CHSL" } ]}, // Add more subcategories like Railways, Police, Teaching etc. ]; case "private-jobs": return [ { title: "Top Job Portals", links: [ { name: "Naukri", url: "https://www.naukri.com" }, { name: "LinkedIn Jobs", url: "https://linkedin.com/jobs" }, { name: "Internshala", url: "https://internshala.com" }, { name: "FreshersWorld", url: "https://www.freshersworld.com" } ]}, { title: "Company Careers", links: [ { name: "TCS Careers", url: "https://www.tcs.com/careers" }, { name: "Infosys Careers", url: "https://www.infosys.com/careers" } ]} ]; case "competitive-exams": return [ { title: "Engineering Exams", links: [ { name: "JEE Main", url: "https://jeemain.nta.nic.in" }, { name: "JEE Advanced", url: "https://jeeadv.ac.in" } ]}, { title: "Medical Exams", links: [ { name: "NEET", url: "https://neet.nta.nic.in" } ]}, { title: "Other Exams", links: [ { name: "CUET", url: "https://cuet.samarth.ac.in" }, { name: "CLAT", url: "https://consortiumofnlus.ac.in" } ]} ]; case "class-wise-info": return [ { title: "5th Class", links: [ { name: "Navodaya Vidyalaya Exam", url: "https://navodaya.gov.in" }, { name: "Pre-Matric Scholarship", url: "https://scholarships.gov.in" } ]}, { title: "9th Class", links: [ { name: "NTSE Info", url: "https://ncert.nic.in/national-talent-examination.php" }, { name: "Science Olympiads", url: "https://sofworld.org" } ]}, { title: "12th & College", links: [ { name: "KVPY", url: "https://kvpy.iisc.ac.in" }, { name: "INSPIRE Scholarships", url: "https://online-inspire.gov.in" } ]} ]; default: return [ { title: "No Data", links: [] } ]; } }

// Chatbot simulation for class-wise prompt const chatbotInput = document.getElementById("chatbot-input"); const chatbotReply = document.getElementById("chatbot-reply");

if (chatbotInput && chatbotReply) { chatbotInput.addEventListener("keypress", (e) => { if (e.key === "Enter") { const text = chatbotInput.value.trim(); if (text.toLowerCase().includes("class")) { chatbotReply.innerHTML = Fetching details for <strong>${text}</strong>...; // Optionally, you can call showSubcategories("class-wise-info"); here } } }); } });

